tiles.setCurrentTilemap(tilemap`level2`)
let fantasma1 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f1111111df.......
    ......fd1111111ddf......
    ......fd111111dddf......
    ......fd111ddddddf......
    ......fd1dfbddddbf......
    ......fbddfcdbbbcf......
    .......f11111bbcf.......
    .......f1b1fffff........
    .......fbfc111bf........
    ........ff1b1bff........
    .........fbfbfff.f......
    ..........ffffffff......
    ............fffff.......
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
sprites.setDataString(fantasma1, "direcao", "esquerda")
let fantasma2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f1111111df.......
    ......fd1111111ddf......
    ......fd111111dddf......
    ......fd111ddddddf......
    ......fd1dfbddddbf......
    ......fbddfcdbbbcf......
    .......f11111bbcf.......
    .......f1b1fffff........
    .......fbfc111bf........
    ........ff1b1bff........
    .........fbfbfff.f......
    ..........ffffffff......
    ............fffff.......
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
sprites.setDataString(fantasma2, "direcao", "esquerda")
tiles.placeOnTile(fantasma1, tiles.getTileLocation(7, 1))
tiles.placeOnTile(fantasma2, tiles.getTileLocation(2, 2))
forever(function () {
    for (let fantasma of sprites.allOfKind(SpriteKind.Enemy)) {
        if (fantasma.tileKindAt(TileDirection.Bottom, sprites.dungeon.floorLight0)) {
            if (sprites.readDataString(fantasma, "direcao") == "esquerda") {
                fantasma.x += -1
            } else {
                fantasma.x += 1
            }
        } else {
            if (sprites.readDataString(fantasma, "direcao") == "esquerda") {
                sprites.setDataString(fantasma, "direcao", "direita")
                fantasma.x += 1
                fantasma.setImage(img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......fd1111111f.......
                    ......fdd1111111df......
                    ......fddd111111df......
                    ......fdddddd111df......
                    ......fbddddbfd1df......
                    ......fcbbbdcfddbf......
                    .......fcbb11111f.......
                    ........fffff1b1f.......
                    ........fb111cfbf.......
                    ........ffb1b1ff........
                    ......f.fffbfbf.........
                    ......ffffffff..........
                    .......fffff............
                    ........................
                    ........................
                    ........................
                    ........................
                    `)
            } else {
                sprites.setDataString(fantasma, "direcao", "esquerda")
                fantasma.setImage(img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f1111111df.......
                    ......fd1111111ddf......
                    ......fd111111dddf......
                    ......fd111ddddddf......
                    ......fd1dfbddddbf......
                    ......fbddfcdbbbcf......
                    .......f11111bbcf.......
                    .......f1b1fffff........
                    .......fbfc111bf........
                    ........ff1b1bff........
                    .........fbfbfff.f......
                    ..........ffffffff......
                    ............fffff.......
                    ........................
                    ........................
                    ........................
                    ........................
                    `)
                fantasma.x += -1
            }
        }
    }
})
